"""First Migration

Revision ID: 48a373a5aa3f
Revises: 
Create Date: 2023-03-31 12:01:20.378713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a373a5aa3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('note_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###
